### PR TITLE
SAX parser to stop URL at closing </loc> fixes #153

### LINKED ISSUE #153: [Sitemaps] SAX parser to stop URL at closing </loc>
The sitemaps SAX parser does not stop a URL at the closing `</loc>`. If there is no closing `</url>` the URL contains all concatenated text, including line breaks. 

Attached [two documents](https://github.com/crawler-commons/crawler-commons/files/824399/sitemaps-invalid-sax-parser.zip) to reproduce the problem. Since both do not validate against the [sitemap schema](http://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd)), the behavior of the DOM parser is acceptable (fails resp. adds only a single URL).

Note: the solution should not break #29 (no `<loc>` element at all).

### PR DESCRIPTION
**Pull request by jnioche**
Fixes the problems reported in #153

### CODE REVIEW

**Comment by jnioche** [comment]
@crawler-commons/committers shall we release after this one?

**Comment by lewismc** [comment]
+1, @jnioche and yes, I am +1 to release. I was planning on re-visiting Sitemap parsing over on Nutch master branch, so I'll make the upgrade to https://github.com/apache/nutch/pull/189 when we release.

**Comment by kkrugler** [comment]
Thanks @jnioche

**Comment by jnioche** [comment]
Thanks for merging @kkrugler

**Pull request merged**
