### PR TITLE
Upgrade to Jdk1.7

### PR DESCRIPTION
**Pull request by lewismc**
Hi Folks,
This PR updates pom.xml to specify javac 1.7 as well as Maven compilation for 1.7.
It then implements all of the localization and charset specification required to comply with the forbidden API's plugin. Additionally it removes all references to System.out.blah which have been replaced by String exception messages and typically wrapped in slf4j logging instances.
Thanks

### CODE REVIEW

**Comment by lewismc** [comment]
Bugger i just noticed that this PR also includes the bloody commits for the validSitemaps branch as well. @Chaiavi can you please merge #82 into master and I will rebase? Thanks.

**Comment by lewismc** [comment]
This PR is now good folks, it's been updated to master.

**Comment by Chaiavi** [comment]
Thanks Lewis

I ran the unit tests and all passed

**Comment by lewismc** [comment]
OK, will wait maybe another day and merge if all good.

**Comment by lewismc** [comment]
Hi @jnioche PR updated to accommodate your suggestions. Quick note on existing String.format usage... we only use it within function calls which return string values. We cannot implementing slf4j logging conventions in such instances. 
I've implemented slf4j conventions in a few other places as well.

**Comment by jnioche** [comment]
> we only use it within function calls which return string values. We cannot implementing slf4j logging conventions in such instances. 

sure, that's not what I was suggesting. Thanks for your work on this

**Comment by kkrugler** [comment]
Hi @lewismc - I didn't see this mentioned in CHANGES.txt

**Comment by lewismc** [comment]
Correct Ken. I used the merge function in the UI and forgot about this. Will update with adhoc commit right now.

**Pull request merged**
