### PR TITLE
Adding support for Google News Sitemaps

### PR DESCRIPTION
**Pull request by michaellavelle**

### CODE REVIEW

**Comment by jnioche** [comment]
thanks @michaellavelle 

We discussed in #36 whether we could have a generic way of handling various extensions instead of hardcoding a mechanism for every single one of them. Any thoughts on that? How would the news extension fit into that?

**Comment by michaellavelle** [comment]
@jnioche Thanks for your message, and for this really useful project!.  A generic way of handling extensions would definitely be a good way to go - some form of SiteMapFactory?   In the meantime,  is this PR something you'd be considering for merge.   This functionality is something we require in the near future and due to the existing private methods of SiteMapParser, it's not possible for us to create our own custom subclass.    An alternative could be to make the methods of SiteMapParser protected - allowing users of the project to add this functionality to their own subclasses - wondered what your thoughts were on this?
Also, would you have any plans for a release soon? - either one including this PR, or for a change to the protected methods - until then we don't have a way to parse Google News Sitemaps using crawler-commons.

**Comment by jnioche** [comment]
Thanks @michaellavelle.

> An alternative could be to make the methods of SiteMapParser protected - allowing users of the project to add this functionality to their own subclasses - wondered what your thoughts were on this?

I would definitely +1 this. Would be a good way of doing until we have a more generic way of dealing with extensions.

Any chance you could contribute a PR for it?

**Comment by jnioche** [comment]
@michaellavelle re-release, things have stalled a bit lately but it would be good to have a release soon. Will probably include #120 (which you are welcome to review if you can) as well as the change to 'protected' we mentioned.

**Comment by jnioche** [comment]
@michaellavelle closing this as I have merged #124

**Pull request closed without merging**
