### PR TITLE
Updated the tests to use parameterizedTest, separating each test

### PR DESCRIPTION
**Pull request by Chaiavi**
Updated the tests to use parameterizedTest, thus making the test file more readable and each normalized pair is now a test in itself, thus making it much easier to identify exactly failure points, and make the rest of the tests pass

### CODE REVIEW

**Comment by Chaiavi** [comment]
This pull request fixes #253

**Comment by jnioche** [comment]
very nice @Chaiavi, thanks

**Comment by Chaiavi** [comment]
@sebastian-nagel @jnioche 
Can my pull request be merged into master ?

**Comment by sebastian-nagel** [comment]
Yes, please merge it. Thanks, @Chaiavi!

**Pull request merged**
