### PR TITLE
Upgrade the project to use Java 11

### LINKED ISSUE #320: Upgrade the project to JDK11
- Update pom.xml
- Compile w/Java 11 as the source, but still generate (via -target) Java 8 class files
- Pay attention to this: [configure the build to avoid using new APIs that are only in Java 11 runtime](https://bugs.openjdk.java.net/browse/JDK-8058150)
- Check for Javac deprecation warnings, anticipate issues with Javaric generation as well
- Run the tests

### PR DESCRIPTION
**Pull request by sebastian-nagel**
(implements / fixes #320)

### CODE REVIEW

**Review by rzo1 — APPROVED** [review]

**Comment by aecio** [comment]
Is there any advantage of compiling and releasing the artifacts for the upcoming version `1.3` using Java 11 (as opposed to keeping it Java 8)? If not, what about merging this PR right after releasing version 1.3? This will give a few extra months for people still on Java 8, and we can start developing the next version using Java 11 features. 

We could also change from version 1.x to 2.x to when we switch to Java 11. This will make clear that the release brings significant changes that might not be compatible. If for any reason, someone still needs Java 8, it would also be possible to release a 1.4 version with the needed features backported to Java 8.

**Comment by sebastian-nagel** [comment]
Hi @aecio,

there is no hurry to force users of crawler-commons to use Java 11. Any objections?

Otherwise I'd move this PR and #320 to 1.4 (we can later decide to name this milestone) and prepare for a release of 1.3...

Notes:
- moved the updates to the changelog which do not belong to the Java 11 upgrade to a separate commit
- for reference, see also the [group discussion](https://groups.google.com/g/crawler-commons/c/xlBv5SLbC-c/m/4S9ohDl5AgAJ)

**Comment by aecio** [comment]
+1 to moving this PR to 1.4. 
Then, in the release notes for 1.3 we can announce that 1.3 is planned to be the last release that supports Java 8.

**Comment by sebastian-nagel** [comment]
Hi @aecio,

> in the release notes for 1.3 we can announce that 1.3 is planned to be the last release that supports Java 8.

I'll put a note to the release announcement mail. The release notes should be final, and who knows whether we decide to delay the upgrade again.

Btw., I had a look at the [dependents of crawler-commons](https://github.com/crawler-commons/crawler-commons/network/dependents): from the more popular ones, at least, [heritrix3](https://github.com/internetarchive/heritrix3) is still based on JDK 8.

**Review by aecio — APPROVED** [review]

**Comment by rzo1** [comment]
@sebastian-nagel @aecio We will have Java 21 (LTS) this year. I guess, that we should move forward here, wdyt?

**Comment by aecio** [comment]
I think we should merge it now.

**Comment by sebastian-nagel** [comment]
Ok, merge confilcts are resolved - will merge as soon as the checks have completed. Thanks!

**Pull request merged**
