### PR TITLE
Added URLFilter interface + BasicURLNormalizer borrowed from Nutch

### PR DESCRIPTION
**Pull request by jnioche**
Related to #74

This PR adds a very simple URLFilter interface with a single method `filter(String URL)` which returns null  if the URL should be filtered out or a modified version of it if it is normalised. This is similar to the approach I used in [storm-crawler](https://github.com/DigitalPebble/storm-crawler/wiki/URLFilters) and is something we meant to do in Nutch a long time ago.

This also contains a modified version of Nutch's BasicURLNormalizer. Later on we could add regex-based URLFilters and normalizers.

### CODE REVIEW

**Comment by Chaiavi** [comment]
Thanks Julien,

Just skimmed and it looks like a good baseline (although I really didn't delve into the code).

I saw a "Main" method in the Basic Normalizer class, maybe we should have it as a "tool" like you did in the sitemaps package ?

**Comment by jnioche** [comment]
Thanks for your comments @Chaiavi 

> I saw a "Main" method in the Basic Normalizer class, maybe we should have it as a "tool" like you did in the sitemaps package ?

yes, it is probably temporary. We could have a generic URLfilter tester class later once we have more than one flavour of filter and a mechanism for declaring them, like the one in [StormCrawler](https://github.com/DigitalPebble/storm-crawler/blob/master/core/src/main/java/com/digitalpebble/storm/crawler/filtering/URLFilters.java) for instance.

**Comment by kkrugler** [comment]
Hi @jnioche,

Looks OK to roll in, though I prefer abstract classes over interfaces. That way if we need to extend it, we don't break every implementation. For example, if we wanted a new API that let the caller specify things like whether to treat a ref (http://domain.com#blah) as a query parameter, we could add this without breaking things.

Separate note - see [SimpleUrlNormalizerTest.java](https://github.com/bixo/bixo/blob/master/src/test/java/bixo/urls/SimpleUrlNormalizerTest.java) in [Bixo](https://github.com/bixo/bixo) for a different set of test normalizations. It would be interesting to see how many of these pass the Nutch-based code.

**Comment by jnioche** [comment]
Thanks @kkrugler 

re-abstract class \: I completely agree. Will change that. I had actually followed the same logic in [stormcrawler's ParsFilter](https://github.com/DigitalPebble/storm-crawler/commit/8e5556e357c1c75861652712938662ab6d9c10ce), should also do the same with the URLFilters there.

There's definitely more to be done on the normalization side. We had listed some things in #74 and #120, this is really work in progress.

**Comment by jnioche** [comment]
Merged in [master c1b3f4b]

**Pull request closed without merging**
